const fs = require('fs');
const path = require('path');

// Function to parse CSV results
function parseCSVResults(filePath) {
    if (!fs.existsSync(filePath)) {
        return null;
    }
    
    const csvData = fs.readFileSync(filePath, 'utf8');
    const lines = csvData.split('\n');
    const headers = lines[0].split(',');
    
    const metrics = {};
    lines.slice(1).forEach(line => {
        if (line.trim()) {
            const values = line.split(',');
            const metricName = values[0];
            if (!metrics[metricName]) {
                metrics[metricName] = [];
            }
            metrics[metricName].push({
                timestamp: values[1],
                value: parseFloat(values[2]) || 0
            });
        }
    });
    
    return metrics;
}

// Function to generate HTML report
function generateHTMLReport(testResults) {
    const html = `
<!DOCTYPE html>
<html>
<head>
    <title>K6 Performance Test Report</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 20px; 
            background-color: #f5f5f5;
        }
        .container { 
            max-width: 1200px; 
            margin: 0 auto; 
            background: white; 
            padding: 20px; 
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header { 
            text-align: center; 
            color: #333; 
            border-bottom: 3px solid #007acc;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .test-section { 
            margin: 30px 0; 
            padding: 20px; 
            border: 1px solid #ddd; 
            border-radius: 5px;
            background: #fafafa;
        }
        .metrics { 
            display: grid; 
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); 
            gap: 15px; 
            margin: 15px 0;
        }
        .metric { 
            background: white; 
            padding: 15px; 
            border-radius: 5px; 
            border-left: 4px solid #007acc;
        }
        .metric-name { 
            font-weight: bold; 
            color: #333;
            font-size: 14px;
        }
        .metric-value { 
            font-size: 24px; 
            color: #007acc; 
            margin: 5px 0;
        }
        .timestamp { 
            color: #666; 
            font-size: 12px;
        }
        .status-pass { color: #28a745; }
        .status-fail { color: #dc3545; }
        .summary {
            background: #e8f4fd;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚀 K6 Performance Test Report</h1>
            <p>Generated on ${new Date().toLocaleString()}</p>
        </div>
        
        <div class="summary">
            <h2>📊 Test Summary</h2>
            <p><strong>Total Tests:</strong> ${Object.keys(testResults).length}</p>
            <p><strong>Status:</strong> <span class="status-pass">✅ Completed</span></p>
        </div>

        ${Object.entries(testResults).map(([testName, results]) => `
        <div class="test-section">
            <h2>🧪 ${testName.replace('results_', '').replace('.csv', '').toUpperCase()} Test</h2>
            ${results ? `
            <div class="metrics">
                ${Object.entries(results).slice(0, 8).map(([metricName, data]) => {
                    const latestValue = data[data.length - 1]?.value || 0;
                    const avgValue = data.reduce((sum, d) => sum + d.value, 0) / data.length || 0;
                    
                    return `
                    <div class="metric">
                        <div class="metric-name">${metricName}</div>
                        <div class="metric-value">${avgValue.toFixed(2)}</div>
                        <div class="timestamp">Latest: ${latestValue.toFixed(2)}</div>
                    </div>
                    `;
                }).join('')}
            </div>
            ` : '<p>❌ No results available</p>'}
        </div>
        `).join('')}
        
        <div class="test-section">
            <h2>📋 Recommendations</h2>
            <ul>
                <li>Monitor response times under different load conditions</li>
                <li>Check error rates and failed requests</li>
                <li>Validate system behavior at peak load</li>
                <li>Review resource utilization metrics</li>
            </ul>
        </div>
        
        <div style="text-align: center; margin-top: 40px; color: #666;">
            <p>Generated by K6 Nagibator2000 🔥</p>
        </div>
    </div>
</body>
</html>
    `;
    
    return html;
}

// Main execution
function main() {
    console.log('🔍 Searching for test results...');
    
    const testResults = {};
    const possibleFiles = [
        'results_smoke.csv',
        'results_grocery.csv', 
        'results_load.csv',
        'results_param.csv',
        'results_stress.csv'
    ];
    
    // Check current directory and artifact directories
    const searchDirs = ['.', 'k6-smoke-results', 'k6-load-results', 'k6-stress-results'];
    
    searchDirs.forEach(dir => {
        if (fs.existsSync(dir)) {
            possibleFiles.forEach(file => {
                const filePath = path.join(dir, file);
                const results = parseCSVResults(filePath);
                if (results) {
                    testResults[file] = results;
                    console.log(`✅ Found results: ${file}`);
                }
            });
        }
    });
    
    if (Object.keys(testResults).length === 0) {
        console.log('⚠️ No test results found, generating empty report...');
        testResults['no_results'] = null;
    }
    
    const html = generateHTMLReport(testResults);
    fs.writeFileSync('report.html', html);
    
    console.log('📊 HTML report generated: report.html');
    console.log(`🎯 Processed ${Object.keys(testResults).length} test result files`);
}

main();